export enum TipoMovimientoStock {
  INGRESO_COMPRA = "INGRESO_COMPRA",
  INGRESO_REQUISICION = "INGRESO_REQUISICION",
  INGRESO_DEVOLUCION_CLIENTE = "INGRESO_DEVOLUCION_CLIENTE",
  INGRESO_TRANSFERENCIA = "INGRESO_TRANSFERENCIA",
  INGRESO_AJUSTE = "INGRESO_AJUSTE",
  SALIDA_VENTA = "SALIDA_VENTA",
  AJUSTE_STOCK = "AJUSTE_STOCK", // nuevo
  ELIMINACION_VENTA = "ELIMINACION_VENTA", // nuevo
  TRANSFERENCIA = "TRANSFERENCIA", // nuevo
  ENTREGA_STOCK = "ENTREGA_STOCK", // nuevo
  SALIDA_DEVOLUCION_PROVEEDOR = "SALIDA_DEVOLUCION_PROVEEDOR",
  SALIDA_AJUSTE = "SALIDA_AJUSTE",
  SALIDA_TRANSFERENCIA = "SALIDA_TRANSFERENCIA",
  SALIDA_REPARACION = "SALIDA_REPARACION",
  ELIMINACION = "ELIMINACION",
  ELIMINACION_STOCK = "ELIMINACION_STOCK",
  INVENTARIO_INICIAL = "INVENTARIO_INICIAL",
  OTRO = "OTRO",
}

/** Array únicamente con las operaciones de ENTRADAS */
export const TiposEntradas = [
  TipoMovimientoStock.INGRESO_COMPRA,
  TipoMovimientoStock.INGRESO_REQUISICION,
  TipoMovimientoStock.INGRESO_DEVOLUCION_CLIENTE,
  TipoMovimientoStock.INGRESO_TRANSFERENCIA,
  TipoMovimientoStock.INGRESO_AJUSTE,
  TipoMovimientoStock.ENTREGA_STOCK,
  TipoMovimientoStock.INVENTARIO_INICIAL,
] as const;

/** Alias de tipo para un valor de TiposEntradas */
export type TipoMovimientoEntrada = (typeof TiposEntradas)[number];
